### ISSUE TITLE
Method to reset a spy

### ISSUE THREAD

**Issue by solsson** [jupiter/node-simple-mock#1]
I felt the need to reset a specific spy to its initial state, with no calls logged.

Right now doing:
```javascript
var simple = require('simple-mock');
// reset a single functino spy in simple-mock, the brutal one-liner way, works for this spec's cases
var reset = function(simpleSpy) {
  simpleSpy.calls.length = simpleSpy.callCount = simpleSpy.called = simpleSpy.lastCall = 0;
};
```

Is there such a method already, that doesn't affect other mocks? If not I can suggest one in my fork.

**Comment by jupiter** [comment]
Thanks, I've made some changes. Let me know if this works for you.

**Comment by solsson** [comment]
Works as expected.

For now the pattern how I use the lib looks like:
```javascript
var mocks = require('simple-mock');

var someTestObject = {
  ...
  someFunction: mocks.spy(function() { return 'a-return-value-if-desired'; })
  ...
};

// somewhere is a procedure-like Mocha test
  expect(someTestObject.someFunction.called).to.be.true();
  someTestObject.someFunction.reset(); // to simplify for it:s below
```

I'm guessing sequences of returnWith will come in handy soon.

Thanks for writing such a nicely scoped lib.

**Comment by jupiter** [comment]
Glad that's what you need. Thanks for the feedback.

In your example, changing to `mocks.stub().returnWith('a-return-value-if-desired')` wouldn't be a big improvement, but if you were expecting multiple calls with different return values, it could help.
