### ISSUE TITLE
Add better promise support (resolvesWith & rejectsWith)

### ISSUE THREAD

**Issue by FredKSchott** [jupiter/node-simple-mock#4]
Hey @jupiter, thanks for the awesome library! Have you thought about adding support for promises? It would make them much easier to work with while testing.

```js
// Currently:
someMock.returnsWith(Promise.resolve(123));
someMock.returnsWith(Promise.reject(new Error()));

// Desired:
someMock.resolvesWith(123);
someMock.rejectsWith(new Error());
```

**Comment by jupiter** [comment]
With Promises natively available in ES6, this is a sensible recommendation. Of course this feature would only work in where it is supported or where a polyfill is provided, but I think that's fine.

**Comment by jupiter** [comment]
Thanks @FredKSchott. Note that I've stuck to the grammar consistent with the other stubbing methods, i.e. resolveWith() and rejectWith() vs resolvesWith() and rejectsWith(). I guess we can add the alternatives, just felt strange to add callsbackWith().

**Comment by FredKSchott** [comment]
Awesome! Agreed on the naming as well, resolveWith/rejectWith make a lot more sense.

Unfortunately this won't work with any user-land promise libraries like [bluebird](https://github.com/petkaantonov/bluebird/), which we're currently using for the time being. Any thoughts on supporting that use-case?

One way to do it would be to add a setup/configure method where you could optionally pass in an instance of the library you'd like to use. Or, maybe you could use `simple.Promise` as an alias to the global Promise, but then allow users to overwrite the property with their own library if needed.

```js
var Promise = require('bluebird');

// Configuration Solution
simple.config({promise: Promise});

// Alias Solution
console.log(simple.Promise); // "[Native Promise Object]"
simple.Promise = Promise;
console.log(simple.Promise); // "[Bluebird Promise Object]"
```

There are probably other solutions as well.

**Comment by FredKSchott** [comment]
Happy to help write up a PR for this btw, if you'd like the help :)

**Comment by jupiter** [comment]
I think I'd want to go with the alias solution. It is a tiny change so I'll do it, but thanks.
